name: month_picker_dialog
description: Internationalized dialog for picking a single month from an infinite list of years.
version: 0.4.0
homepage: https://github.com/hmkrivoj/month_picker_dialog

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ">=0.1.0<2.0.0"
  #flutter_cupertino_localizations: ^1.0.1
  rxdart: ^0.26.0

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # To add assets to your plugin package, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.io/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.
fonts:
  - family: Bahij_TheSansArabic_bold
    fonts:
      - asset: assets/fonts/Bahij_TheSansArabic-Bold.ttf
  - family: TheSans_Plain
    fonts:
      - asset: assets/fonts/TheSans_Plain.ttf
  - family: Bahij_TheSansArabic_light
    fonts:
      - asset: assets/fonts/Bahij_TheSansArabic-Light.ttf
  - family: Bahij_TheSansArabic
    fonts:
      - asset: assets/fonts/Bahij_TheSansArabic-Plain.ttf
  - family: Montserrat-Bold
    fonts:
      - asset: assets/fonts/Montserrat-Bold.ttf
  - family: MSF-UI-Display-Regular
    fonts:
      - asset: assets/fonts/SF-UI-Display-Regular.otf
  - family: SF-Pro-Text-Regular
    fonts:
      - asset: assets/fonts/SF-Pro-Text-Regular.otf
  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.io/custom-fonts/#from-packages
